### ISSUE TITLE
Supporting FTP servers that don't have the MLSD command

### ISSUE THREAD

**Issue by Rokke** [salim-lachdhaf/ftpConnect#12]
When connecting to a Microsoft FTP server (or other old FTP server all commands except sizeFile isn't working.
Looking from logs it's failing on the command MLSD that is called also before the GET command because it's also then calling the MLSD.
Exception received:
FTPException (FTPException: Can't get content of directory. (Response: 500 'MLSD ': command not understood.))

**Comment by salim-lachdhaf** [comment]
We already handled this servers in last version of the plugin, 
Use it something like : 
`FtpConnect.listDirectoryContent(cmd: DIR_LIST_COMMAND.LIST))`

**Comment by Rokke** [comment]
Thanks for quick reply
I was unable to use the DIR_LIST_COMMAND.LIST from my client application.
I forked the project and moved this (and the TransferMode) to the root folder and then I was able to use that option.
I also made 2 other changes:
* A callback to be able to add progress when downloading file
* The IIS FTP server that I was using returned only 2 last digits so it's handling this.
Please tell me if you would like to add it in your project

**Comment by salim-lachdhaf** [comment]
this is not clear : _**I was unable to use the DIR_LIST_COMMAND.LIST from my client application.**_
however; if you import this you will have access `import 'package:ftpconnect/src/commands/directory.dart';
`

yes why not , it seems interesting just add the full signature to the `onProgress `function like `Function(int x)` or declare a `typeDef `to force user to enter the correct function format signature ;)
and try to prevent to use "20" use current year digits , suppose we are in 2120 ! use a generic one (get the two digitis from the current year not hard code it), and why you remove `dataSocket.close` !

i'm waiting for your pull request in dev branch ;) this will be usefull espacially the loading one. thank you.

**Comment by Rokke** [comment]
With regards to the import I managed to get that working with adding the import you described but I just get a warning in VSCode: "Don't import implementation files from another package."
And also it's not able to auto locate the package when it's down in that path so that's why I moved it.
I didn't remove the dataSocket.close() (line 50)
I first thought of using the year instead of hardcoding "20" but I just thought that spending the extra cycles each time to calculate this instead of thinking that it will still be used in 80 years was waste, but I will change this.

I'm not sure how to add my code yet but I guess it's easy so I will figure it out after I have fixed the year and the fuction signature.
Thanks

**Comment by Rokke** [comment]
I'm finished with the changes but I will wait for the pull until you tell me if I should use the import as you told me (with the warning and not auto locating the package) or if I should keep the DIR_LIST_COMMAND and TransferMode in the ftpclient.dart file
After this I will add the code.

**Comment by salim-lachdhaf** [comment]
I choose your modif over old implementation. thank you.
