### ISSUE TITLE
Not closing the File handle completely

### ISSUE THREAD

**Issue by Rokke** [salim-lachdhaf/ftpConnect#18]
When sending the same file several times it doesn't close the file inbetween and failing.
It's the same problem if deleting the file right after I upload it (before disconnecting).
As an example if I do the following:
await ftp.uploadFile(File('somefile.txt', sRemoteName: 'somefile1.txt');
await ftp.uploadFile(File('somefile.txt', sRemoteName: 'somefile2.txt');
it fails on the second because it's saying that the file is allready in use

If I add to the line 50(in fileUpload.dart):
    readStream = null;
Then it works fine (you also need to then change the final readStream to Stream readStream

**Comment by salim-lachdhaf** [comment]
thank you for reporting that, this will be fixed in the next release
