### ISSUE TITLE
fails if ftp server cannot enter passive mode

### ISSUE THREAD

**Issue by paultz54** [salim-lachdhaf/ftpConnect#19]
PASV works ok on my isp's server but EPSV returns 550 permission denied
the server is ftp.users.on.net

**Comment by paultz54** [comment]
PASV works ok on my isp's server but  EPSV returns 500 permission denied
the server is ftp.users.on.net

**Comment by paultz54** [comment]
After googling around a bit it seems this might be a firewall problem on my side 
another dart ftp package (ftclient) works using PASV - but crashes elsewhere

**Comment by salim-lachdhaf** [comment]
do you have a demo user and password to test and fihure out the problem if exist, please pass tjese informations in private email to fix that.

**Comment by paultz54** [comment]
thanks for offering to look at it Salim i've changed my password on the server but i dont know how to
contact you privately  but if you can email me  paultz (at) that famous email server run by the dart teams financiers
(starts with a g) ill let you know the login -  also have asked internode isp support to give you a testing account

**Comment by salim-lachdhaf** [comment]
you can contact on the mail indicated on pub.dev

**Comment by paultz54** [comment]
private mail sent

**Comment by paultz54** [comment]
I still have the problem 
PASV works ok on my isp's server but EPSV returns 550 permission denied
the server is ftp.users.on.net

heres the log from ftpconnect
[21.03.2021 16:13:18.616] Connected!
[21.03.2021 16:13:19.394] > CWD upload
[21.03.2021 16:13:20.345] < 550 Failed to change directory.
[21.03.2021 16:13:31.120] > EPSV
[21.03.2021 16:13:31.329] < 550 Permission denied.
Error: FTPException: Could not start Passive Mode (Response: 550 Permission denied.)

**Comment by salim-lachdhaf** [comment]
check the new version
