### ISSUE TITLE
Error: FTPException: Timeout reached for Receiving response ! (Response: null) - 534 Policy requires SSL.

### ISSUE THREAD

**Issue by jjoelp** [salim-lachdhaf/ftpConnect#20]
Hi !

I'm using ftp to upload/download file from server directory.
When connecting to FTP, It return timeout error. 
Here is the log :

> I/flutter (29067): [30.12.2020 17:22:30.984] Connecting...
I/flutter (29067): [30.12.2020 17:22:31.095] > USER xxxxx
I/flutter (29067): [30.12.2020 17:22:31.301] < 220 Microsoft FTP Service
I/flutter (29067): 534 Policy requires SSL.
I/flutter (29067): [30.12.2020 17:22:31.303] > PASS xxxxx
I/flutter (29067): [30.12.2020 17:22:31.508] < 503 Login with USER first.
I/flutter (29067): Error: FTPException: Timeout reached for Receiving response ! (Response: null)

My code : 

`
uploadPhoto(File` file) async {
        FTPConnect ftpConnect = FTPConnect(
            ApiUrls.ftp.url,
            port: ApiUrls.ftp.port,
            user: ApiUrls.ftp.user,
            pass: ApiUrls.ftp.passwword,
            debug: true
        );

        try {
            await _log('Connecting to FTP ...');
            await ftpConnect.connect();
            await ftpConnect.changeDirectory('Photos');
            await _log('Uploading ...');
            await ftpConnect.uploadFile(file);
            await _log('file uploaded sucessfully');
            await ftpConnect.disconnect();
            await file.delete();
        } catch (e) {
            await _log('Error: $e');
        }
    }`

Is there a way to solve this ?

**Comment by salim-lachdhaf** [comment]
i see your issue, your ftp require an ssl connexion but we do not that in the current version,   is it possible to pass me an example of the ftp that require ssl in private via eMail to add this feature to the pluging ?

**Comment by salim-lachdhaf** [comment]
i published a beta verion for that (0.2.1-sslTest), could you test it ?

**Comment by jjoelp** [comment]
Ok ! I'm testing it.

**Comment by jjoelp** [comment]
It throw an other exception :

> FTPException: Could not connect to url (port) (Response: HandshakeException: Handshake error in client (OS Error:
WRONG_VERSION_NUMBER(tls_record.cc:242)))

**Comment by salim-lachdhaf** [comment]
otherwise try this version  `0.2.1-sslTest2` , i add some an option to accept all kind of certificates

**Comment by xreManu** [comment]
Hi :) !
I' tried with 0.2.1-sslTest2 version but it's return the same error
FTPException: Could not connect to url (port) (Response: HandshakeException: Handshake error in client (OS Error: WRONG_VERSION_NUMBER(tls_record.cc:242)))

**Comment by salim-lachdhaf** [comment]
try to change port to use TLS instead of SSL

**Comment by xreManu** [comment]
Hi! 
How to change port to use TLS instead of SSL with this version "0.2.1-sslTest2"

**Comment by salim-lachdhaf** [comment]
i think your server has several port ! , try them, or contact the your system admin
https://github.com/flutter/flutter/issues/23767

**Comment by xreManu** [comment]
Now we try to get the certificate file from our system admin and then setting the SecurityContext.

**Comment by salim-lachdhaf** [comment]
you confirm that in fileZilla it works fine ?

**Comment by xreManu** [comment]
Hi!
I confirm that it works in fileZilla.

**Comment by salim-lachdhaf** [comment]
did you added any special setting in fileZilla ?

**Comment by xreManu** [comment]
No! we don't add special setting in fileZilla just user, password and port

**Comment by xreManu** [comment]
With source code of this version "0.2.1-sslTest2" -> I try to set a certificate file (.pem) to the useCertificateChain of the SecurityContext but it return the same error =>
FTPException: Could not connect to url (port) (Response: HandshakeException: Handshake error in client (OS Error: WRONG_VERSION_NUMBER(tls_record.cc:242)))

**Comment by salim-lachdhaf** [comment]
sorry , but are you sure that your using the code of "0.2.1-sslTest2" from pub.dev ? because i didn't commit yet this changes

**Comment by xreManu** [comment]
You didn't commit it yet but I download source code of "0.2.1" and I changed it with the modification I saw  in "0.2.1-sslTest2" :).

**Comment by salim-lachdhaf** [comment]
i pushed the modification in the dev branch, however, have you any test server that i could use to test to solve the issue or anything else could help ?

**Comment by xreManu** [comment]
Now we haven't a test server.

**Comment by hksolo27** [comment]
Hmmm interested

**Comment by salim-lachdhaf** [comment]
check the new version
