### ISSUE TITLE
How can I get the download/upload progress status?

### ISSUE THREAD

**Issue by burekas7** [salim-lachdhaf/ftpConnect#21]
Hi,
First thanks for this package.

My question is if I want to show to the user the current status of the upload/download progress how I can I do that with this package?

Thanks.

**Comment by salim-lachdhaf** [comment]
for now we added the progress only for uploading, the download will be available in the next version.

    ```
//test upload file 
    void testUploadProgress(double p, int r) {
      print('uploaded :$r byte =========> $p%');
    }


        await _ftpConnect.uploadFile(await _fileMock(),
            onProgress: testUploadProgress);
```

**Comment by burekas7** [comment]
@salim-lachdhaf 

Thanks.
I'll be waiting for updates.

By the way, what is the frequency that the  values is getting update?
On each second, each buffer size....?

How basically does the upload works, does it seperate the file into buffers?

**Comment by salim-lachdhaf** [comment]
you can check the source code, it is an open source package
