### ISSUE TITLE
FTPS support

### ISSUE THREAD

**Issue by Archiware** [salim-lachdhaf/ftpConnect#23]
I am currently searching for a way to implement the full spectrum of FTP functionality into a Flutter cross platform project, featuring FTP, SFTP and FTPS. Not wanting to reinvent the wheel, I found your package to cover the base FTP functionality pretty nicely, so I'll definitely build upon that.

Knowing that SFTP would be more appropriate inside a SSH package than this one, I'm just wondering if there are any plans on implementing FTPS. If you're not actively considering it, would you be open to integrate an implementation by pull request from someone else in the future?

Just making sure how to best place my own efforts so most people benefit from it in the end. :)

Cheers!

**Comment by salim-lachdhaf** [comment]
yes , FTPS devs are in progress.

**Comment by salim-lachdhaf** [comment]
check the new version
