### ISSUE TITLE
Null safety compatibility

### ISSUE THREAD

**Issue by Aguape21** [salim-lachdhaf/ftpConnect#25]
Is there a provision to enable for Null safety compatibility?

**Comment by robertoltrocha** [comment]
Hi,
I have the same question.

**Comment by salim-lachdhaf** [comment]
hi ,we will add nullSafety in the next release

**Comment by Aguape21** [comment]
Obrigado  @salim-lachdhaf !
Thanks    @salim-lachdhaf !

**Comment by robertoltrocha** [comment]
Hi @salim-lachdhaf.
Thank you for your attention, we are with the project unable to update because of this dependency.

**Comment by Firefnix** [comment]
Does anyone know when will this version be published? As @robertoltrocha said, it is impossible to `pub get` a null-safe project without having only null-safe packages, so not having a null-safe version is kinda annoying.
For your information, Dart provides simple tools to migrate packages (`dart migrate`), and the whole process doesn't take more than a few minutes to complete.
Anyways, I would like to thank you for this awesome package!

**Comment by robertoltrocha** [comment]
Hello everyone,
I looked for another similar package but did not found it. This package is unique.
I don't understand how Flutter doesn't have this native feature.
Let's wait for the new release.
Thanks,

**Comment by Firefnix** [comment]
>  I don't understand how Flutter doesn't have this native feature.
The FTP protocol is getting pretty old, so it is understandable that Dart doesn't come with a native FTP package (even if other languages, like Python, have one).

I made a pull request (#29) for the migrated package, and all the tests seem to pass. Waiting for @salim-lachdhaf and/or other reviewers to validate it! If you can't wait for the  null-safe version to be released, you can still use the package I made (by doing a local clone, for instance).

**Comment by robertoltrocha** [comment]
Hey guys,
Any predictions for the new release?
thanks.

**Comment by salim-lachdhaf** [comment]
this weekend.

**Comment by Akash9151** [comment]
@salim-lachdhaf , Any update..?

**Comment by robertoltrocha** [comment]
Hello everyone,
I cloned the package and updated the dependencies and to adjust to null safety, I had to change some list instances to List.empty (grow ....: true)
Very easy, the system itself points out where to change.

It seems that everything worked correctly.

**Comment by salim-lachdhaf** [comment]
check the new version
