### ISSUE TITLE
Error for no reason

### ISSUE THREAD

**Issue by isjain35** [salim-lachdhaf/ftpConnect#3]
When I try to connect to my ftp server, An error arises saying **FTPException: Wrong password (Response: 331 User _username here_ OK. Password required)** although I provided it earlier and all username and password are correct, I checked it thrice.

_Launching lib\main.dart on GM1901 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Waiting for GM1901 to report its views...
Debug service listening on ws://127.0.0.1:59209/sbinX0kgRHE=/ws
Syncing files to device GM1901...
I/Surface (20823): opservice is null false
D/FilePickerUtils(20823): Allowed file extensions mimes: [image/jpeg, application/pdf, application/msword]
D/FilePickerDelegate(20823): Selected type */*
D/DecorView(20823): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@917ac34[MainActivity]
D/FilePickerDelegate(20823): [SingleFilePick] File URI:content://com.android.providers.media.documents/document/image%3A52271
I/FilePickerUtils(20823): Caching from URI: content://com.android.providers.media.documents/document/image%3A52271
D/DecorView(20823): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@917ac34[MainActivity]
D/FilePickerUtils(20823): File loaded and cached at:/data/user/0/com.me.admin/cache/file_picker/IMG-20201006-WA0016.jpg
D/FilePickerDelegate(20823): File path:[com.mr.flutter.plugin.filepicker.FileInfo@4bd3eda]
I/flutter (20823): FTPException: Wrong password (Response: 331 User userfirst OK. Password required)_

**Comment by salim-lachdhaf** [comment]
Please check if there is no extra space in your login or password

**Comment by isjain35** [comment]
@salim-lachdhaf there is nothing like that.

**Comment by salim-lachdhaf** [comment]
is the issue still there ?

**Comment by isjain35** [comment]
There's no issue now bcoz I changed the package and way of implementation in my code...
But please find out where was the problem exactly arising from bcoz I would like to use ftpconnect in my future projects...

**Comment by salim-lachdhaf** [comment]
normaly your issue is fixed. try the new version and keep me updated
