### ISSUE TITLE
performance when uploading multiple files

### ISSUE THREAD

**Issue by simion** [salim-lachdhaf/ftpConnect#31]
Hi. 

First of all thank you for this awesome library. I'm using it for https://homestash.app to upload photos/video via FTP.

I've noticed that uploading via flutter/ftpconnect is much slower that using any ftp client.

I've added some prints in `fileUpload.dart` -> `FileUpload.uploadFile()` and i've noticed the library does some operations each time i call uploadFile, operations which take more time than the upload itself.

I've made a small video demonstrating this issue: https://www.youtube.com/watch?v=20fD6N_7lTk

Would it be possible to reuse some operations / skip calling them, like "set transfer mode" / "open socket" / close socket in order to achieve mych faster loop-upload?

Thanks.

**Comment by salim-lachdhaf** [comment]
the current behavior is completly normal i dobnot see any possible optimisation.
how ever, we could add an fonction that send multi files in the same time, like this we will pass by open socket , mode .... only once, and this could improve speed very well.

**Comment by simion** [comment]
> however, we could add an fonction that send multi files in the same time

indeed, reusing "transfer mode" and open socket will save alot of time.
However, for this to work, at least in my use case, i would need a way to stop the upload (without finishing the entire list of uploads), and also a sort of progress / callback after each file is uploaded.

Wouldn't this be easier to expose the initialization/open part (set transfer mode / open socket), to external api so that i can manually call this, then uploadFile in a loop, then manually close the socket?

**Comment by salim-lachdhaf** [comment]
i don't think it's a good idea to make that manually, the user of plugin will be confused, it will made plugin understanding harder...
the best solution is adding a new function that has paramter a list of file, of course uploding files is a `Future` so you can cancel it as you want ...

**Comment by simion** [comment]
Yes, and that progress callback is also needed. 😁

**Comment by simion** [comment]
Do you think it's difficult to implement an `uploadMultiple` method which accepts a list of files, and uploads them in a loop, reusing transfer mode, passive mode, and dataSocket?
I've also noticed that `TransferUtil.checkTransferOK` sometimes may be slow. Does this method download the file for checking it's integrity?

**Comment by simion** [comment]
I could try to contribute on this, but i need to study FTP protocol before, to understand all commands which are being sent

**Comment by simion** [comment]
So, bg improvement after caching "transfer mode passive" in https://github.com/salim-lachdhaf/ftpConnect/pull/32/files 
Searching for more ideas i could make it faster. 
FileZilla moves blaxing fast compared to a flutter ap using this library. Not sure why.

**Comment by salim-lachdhaf** [comment]
the fastest way will be by adding a new function that has as parameter a list of file to export to ftp.
