### ISSUE TITLE
I got HandshakeException: Handshake error in client, when I set isSecure true

### ISSUE THREAD

**Issue by falll2000** [salim-lachdhaf/ftpConnect#35]
Hi~!

I want connect ftps, so I set isSecure is true

but I got message below

Exception:  FTPException: Could not connect to 61.220.128.128 (47809) (Response: HandshakeException: Handshake error in client (OS Error: WRONG_VERSION_NUMBER(tls_record.cc:242))) 

I had test library version include 1.0.0 and 0.2.1-sslTest2, error message is the same.

I used filezilla to test my ftp server, connection type is explicit mode, I can connect to ftps server.

thanks.

**Comment by falll2000** [comment]
I try to set my ftp server to implicit mode, and this library work fine.

So, I think ftpconnect just work fine in implicit mode, but not explicit mode.

Can you add explicit mode in this library? thanks

**Comment by simion** [comment]
Also having this issue, trying to connect to a FTP server on  ASUS RT-AC66U  router

**Comment by federicofederigi** [comment]
I have the same problem, but implicit mode don't work.
I use self-signed certificate of filezilla server, Can i use selg-signed certificate?
thanks

**Comment by LmpGuillaumeLP** [comment]
I get the same message when i try to connect to my SFTP server.
Has anyone managed to solve this problem?

**Comment by salim-lachdhaf** [comment]
check the last version, to try secure mode try `isSecured` option
