### ISSUE TITLE
Unzip file compressed with password

### ISSUE THREAD

**Issue by federicofederigi** [salim-lachdhaf/ftpConnect#37]
I Compress a file con 7Zip with a CryptoZip password 'aaaaaaaa'  (with winzip i have the same problem)
After download file with .downloadFileWithRetry(fileName, downloadedFile, pRetryCount: 2);
when unzip the file with  .unZipFile(downloadedFile, downloadedFile.parent.path, password: 'aaaaaaaa', );

Appear the file decompressed regulary.
But all files are corrupt, (. . .  txt file with strange characters)
i have the same problem if i unzip the file.zip with a wrong password

very thanks

**Comment by federicofederigi** [comment]
I'm using Zip with 7Zip

with compression Deflate or BZip2 or no compression. .  . i have the problem . . .

or compress and crypto of winzip    with windows 7

and decompress with flutter in viritualized android 24

can i make other test to solve the problem?

very thanks

Federico

**Comment by salim-lachdhaf** [comment]
problem comes from the `archive` plugin not this plugin.
