### ISSUE TITLE
FTPException: Could not start Passive Mode (Response: 500 Unknown command

### ISSUE THREAD

**Issue by BFSistemi** [salim-lachdhaf/ftpConnect#43]
hi

when I try upload a file in a FTP's folder return this error:

FTPException: Could not start Passive Mode (Response: 500 Unknown command

this is the debug log:

I/flutter ( 7546): [09.12.2021 13:02:46.756] Connecting...
I/flutter ( 7546): [09.12.2021 13:02:47.283] > USER xxxxxx@aruba.it
I/flutter ( 7546): [09.12.2021 13:02:47.927] < 220-#
I/flutter ( 7546): 220-#
I/flutter ( 7546): 220-#  Aruba.it
I/flutter ( 7546): 220-#  The Web Hosting Company
I/flutter ( 7546): 220-#
I/flutter ( 7546): 220-#
I/flutter ( 7546): 220 This is a private system - No anonymous login
I/flutter ( 7546): 331 User xxxxxx@aruba.it OK. Password required
I/flutter ( 7546): [09.12.2021 13:02:47.935] > PASS xxxxxxxx
I/flutter ( 7546): [09.12.2021 13:02:48.622] < 230 OK. Current restricted directory is /
I/flutter ( 7546): [09.12.2021 13:02:48.629] Connected!
I/flutter ( 7546): [09.12.2021 13:02:48.642] > CWD /www.mysite.com/flutter/bf/ordini/
I/flutter ( 7546): [09.12.2021 13:02:49.280] < 250 OK. Current directory is /www.mysite.com/flutter/bf/ordini
I/flutter ( 7546): [09.12.2021 13:03:04.016] Upload File: /data/user/0/com.example.flutterbf/app_flutter/flutter_dest.csv
I/flutter ( 7546): [09.12.2021 13:03:04.028] > TYPE I
I/flutter ( 7546): [09.12.2021 13:03:04.638] < 200 TYPE is now 8-bit binary
I/flutter ( 7546): [09.12.2021 13:03:04.642] > EPSV
I/flutter ( 7546): [09.12.2021 13:03:05.268] < 500 Unknown command
E/flutter ( 7546): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FTPException: Could not start Passive Mode (Response: 500 Unknown command
E/flutter ( 7546): )
E/flutter ( 7546): #0      TransferUtil.enterPassiveMode
E/flutter ( 7546): <asynchronous suspension>
E/flutter ( 7546): #1      FileUpload.uploadFile
E/flutter ( 7546): <asynchronous suspension>
E/flutter ( 7546): #2      ftp
E/flutter ( 7546): <asynchronous suspension>
E/flutter ( 7546):

any ideas?
tnx
Fabio

**Comment by simion** [comment]
Send `supportIPV6=false` and it will use `PASV` instead of `EPSV`. Not all fto servers support EPSV

**Comment by BFSistemi** [comment]
perfect! 
it works
thanks
