### ISSUE TITLE
Errors in server connections (Connection refused)

### ISSUE THREAD

**Issue by Aguape21** [salim-lachdhaf/ftpConnect#44]
I made some changes to the package to resolve issues regarding the "Connection refused" error.
**/transferUtil.dart**
`  static Future<String> checkIsConnectionAccepted(FTPSocket socket) async {
    String sResponse = await socket.readResponse();
    if (!sResponse.startsWith('150') _&& !sResponse.startsWith('125')_) {
      throw FTPException('Connection refused. ', sResponse);
    }
    return sResponse;
  }`

**Comment by salim-lachdhaf** [comment]
what changes and in which case you have this error ?
