### ISSUE TITLE
upload image issue?

### ISSUE THREAD

**Issue by federico2390** [salim-lachdhaf/ftpConnect#46]
when I try to save an image the file is created with the correct name of the file but the size is ever 0 byte.

receive this erro: type 'SocketException' is not a subtype of type 'String?'

**Comment by salim-lachdhaf** [comment]
could past an example

**Comment by federico2390** [comment]
``
Future<void> _uploadFiles(
      String folder, category, name, List<ImageObject> images) async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    String host = prefs.getString('host')!,
        user = prefs.getString('user')!,
        password = prefs.getString('password')!;

    if (host.isNotEmpty && user.isNotEmpty && password.isNotEmpty) {
      ftpConnect = FTPConnect(host, user: user, pass: password);
      try {
        await ftpConnect!.connect();
        await ftpConnect!.makeDirectory(folder);
        await ftpConnect!.changeDirectory(folder);
        await ftpConnect!.createFolderIfNotExist(name);
        await ftpConnect!.changeDirectory(name);
        await ftpConnect!
            .uploadFileWithRetry(File(images.first.modifiedPath))
            .showProgressDialog(
          context,
          message: const Text('In corso...'),
          title: const Text('Caricamento immagine'),
          onProgressError: (error) {
            debugPrint(error);
          },
        );
        debugPrint('file uploaded sucessfully');
        await ftpConnect!.disconnect();
      } catch (e) {
        debugPrint('ERRORE: ${e.toString()}');
      }
    }
  }
``

**Comment by federico2390** [comment]
I/flutter ( 5139): [22.01.2022 09:21:39.072] Connecting...
I/flutter ( 5139): [22.01.2022 09:21:39.163] > USER sitolab@outlook.it
I/flutter ( 5139): [22.01.2022 09:21:39.988] < 220 Microsoft FTP Service
I/flutter ( 5139): 331 Password required
I/flutter ( 5139): [22.01.2022 09:21:39.992] > PASS Leccesidentro@1
I/flutter ( 5139): [22.01.2022 09:21:40.806] < 230 User logged in.
I/flutter ( 5139): [22.01.2022 09:21:40.807] Connected!
I/flutter ( 5139): [22.01.2022 09:21:40.813] > MKD Settimana 4 - 2022
I/flutter ( 5139): [22.01.2022 09:21:41.631] < 550 Cannot create a file when that file already exists.
I/flutter ( 5139): [22.01.2022 09:21:41.634] > CWD Settimana 4 - 2022
I/flutter ( 5139): [22.01.2022 09:21:42.446] < 250 CWD command successful.
I/flutter ( 5139): [22.01.2022 09:21:42.451] > CWD Pippo
I/flutter ( 5139): [22.01.2022 09:21:43.264] < 250 CWD command successful.
I/flutter ( 5139): [22.01.2022 09:21:43.265] > CWD Pippo
I/flutter ( 5139): [22.01.2022 09:21:44.076] < 550 The system cannot find the file specified.
I/flutter ( 5139): [22.01.2022 09:21:44.082] Upload File: /storage/emulated/0/Android/data/com.moeasy.are/cache/CAP686775070897955497_cropped3127237557520879615.jpg
I/flutter ( 5139): [22.01.2022 09:21:44.085] Entering transfer mode TransferMode.binary
I/flutter ( 5139): [22.01.2022 09:21:44.086] > TYPE I
I/flutter ( 5139): [22.01.2022 09:21:44.895] < 200 Type set to I.
I/flutter ( 5139): [22.01.2022 09:21:44.897] > PASV
I/flutter ( 5139): [22.01.2022 09:21:45.707] < 227 Entering Passive Mode (192,168,1,85,8,56).
I/flutter ( 5139): [22.01.2022 09:21:45.721] > STOR CAP686775070897955497_cropped3127237557520879615.jpg
I/flutter ( 5139): [22.01.2022 09:21:45.723] Opening DataSocket to Port 2104
I/flutter ( 5139): ERRORE_onProgressError: SocketException: OS Error: Connection refused, errno = 111, address = 192.168.1.85, port = 56804
I/flutter ( 5139): file uploaded sucessfully
I/flutter ( 5139): [22.01.2022 09:23:00.445] Disconnecting...
I/flutter ( 5139): [22.01.2022 09:23:00.445] > QUIT
I/flutter ( 5139): [22.01.2022 09:23:01.457] < 150 Opening BINARY mode data connection.
I/flutter ( 5139): 425 Data channel timed out.
I/flutter ( 5139): 221 Goodbye.
I/flutter ( 5139): [22.01.2022 09:23:01.463] Disconnected!

### **The file is first uploaded to the ftp server but with a size of 0 bytes, then at the end of the uploading process it is deleted ... Why?**

**Comment by federico2390** [comment]
I/flutter ( 5139): [22.01.2022 09:21:39.072] Connecting...
I/flutter ( 5139): [22.01.2022 09:21:39.163] > USER ****@****.it
I/flutter ( 5139): [22.01.2022 09:21:39.988] < 220 Microsoft FTP Service
I/flutter ( 5139): 331 Password required
I/flutter ( 5139): [22.01.2022 09:21:39.992] > PASS *****
I/flutter ( 5139): [22.01.2022 09:21:40.806] < 230 User logged in.
I/flutter ( 5139): [22.01.2022 09:21:40.807] Connected!
I/flutter ( 5139): [22.01.2022 09:21:40.813] > MKD Settimana 4 - 2022
I/flutter ( 5139): [22.01.2022 09:21:41.631] < 550 Cannot create a file when that file already exists.
I/flutter ( 5139): [22.01.2022 09:21:41.634] > CWD Settimana 4 - 2022
I/flutter ( 5139): [22.01.2022 09:21:42.446] < 250 CWD command successful.
I/flutter ( 5139): [22.01.2022 09:21:42.451] > CWD Pippo
I/flutter ( 5139): [22.01.2022 09:21:43.264] < 250 CWD command successful.
I/flutter ( 5139): [22.01.2022 09:21:43.265] > CWD Pippo
I/flutter ( 5139): [22.01.2022 09:21:44.076] < 550 The system cannot find the file specified.
I/flutter ( 5139): [22.01.2022 09:21:44.082] Upload File: /storage/emulated/0/Android/data/com.moeasy.are/cache/CAP686775070897955497_cropped3127237557520879615.jpg
I/flutter ( 5139): [22.01.2022 09:21:44.085] Entering transfer mode TransferMode.binary
I/flutter ( 5139): [22.01.2022 09:21:44.086] > TYPE I
I/flutter ( 5139): [22.01.2022 09:21:44.895] < 200 Type set to I.
I/flutter ( 5139): [22.01.2022 09:21:44.897] > PASV
I/flutter ( 5139): [22.01.2022 09:21:45.707] < 227 Entering Passive Mode (192,168,1,85,8,56).
I/flutter ( 5139): [22.01.2022 09:21:45.721] > STOR CAP686775070897955497_cropped3127237557520879615.jpg
I/flutter ( 5139): [22.01.2022 09:21:45.723] Opening DataSocket to Port 2104
I/flutter ( 5139): ERRORE_onProgressError: SocketException: OS Error: Connection refused, errno = 111, address = 192.168.1.85, port = 56804
I/flutter ( 5139): file uploaded sucessfully
I/flutter ( 5139): [22.01.2022 09:23:00.445] Disconnecting...
I/flutter ( 5139): [22.01.2022 09:23:00.445] > QUIT
I/flutter ( 5139): [22.01.2022 09:23:01.457] < 150 Opening BINARY mode data connection.
I/flutter ( 5139): 425 Data channel timed out.
I/flutter ( 5139): 221 Goodbye.
I/flutter ( 5139): [22.01.2022 09:23:01.463] Disconnected!

### **The file is first uploaded to the ftp server but with a size of 0 bytes, then at the end of the uploading process it is deleted ... Why?**

**Comment by salim-lachdhaf** [comment]
try without `.showProgressDialog` and use `onProgress` parameter

**Comment by federico2390** [comment]
Tryed I receive the error on top

I/flutter ( 5139): [22.01.2022 09:21:39.072] Connecting...
I/flutter ( 5139): [22.01.2022 09:21:39.163] > USER @.it
I/flutter ( 5139): [22.01.2022 09:21:39.988] < 220 Microsoft FTP Service
I/flutter ( 5139): 331 Password required
I/flutter ( 5139): [22.01.2022 09:21:39.992] > PASS *****
I/flutter ( 5139): [22.01.2022 09:21:40.806] < 230 User logged in.
I/flutter ( 5139): [22.01.2022 09:21:40.807] Connected!
I/flutter ( 5139): [22.01.2022 09:21:40.813] > MKD Settimana 4 - 2022
I/flutter ( 5139): [22.01.2022 09:21:41.631] < 550 Cannot create a file when that file already exists.
I/flutter ( 5139): [22.01.2022 09:21:41.634] > CWD Settimana 4 - 2022
I/flutter ( 5139): [22.01.2022 09:21:42.446] < 250 CWD command successful.
I/flutter ( 5139): [22.01.2022 09:21:42.451] > CWD Pippo
I/flutter ( 5139): [22.01.2022 09:21:43.264] < 250 CWD command successful.
I/flutter ( 5139): [22.01.2022 09:21:43.265] > CWD Pippo
I/flutter ( 5139): [22.01.2022
I/flutter ( 5139): [22.01.2022 09:21:44.082] Upload File: /storage/emulated/0/Android/data/com.moeasy.are/cache/CAP686775070897955497_cropped3127237557520879615.jpg
I/flutter ( 5139): [22.01.2022 09:21:44.085] Entering transfer mode TransferMode.binary
I/flutter ( 5139): [22.01.2022 09:21:44.086] > TYPE I
I/flutter ( 5139): [22.01.2022 09:21:44.895] < 200 Type set to I.
I/flutter ( 5139): [22.01.2022 09:21:44.897] > PASV
**I/flutter ( 5139): [22.01.2022 09:21:45.707] < 227 Entering Passive Mode (192,168,1,85,8,56).**
I/flutter ( 5139): [22.01.2022 09:21:45.721] > STOR CAP686775070897955497_cropped3127237557520879615.jpg
**I/flutter ( 5139): [22.01.2022 09:21:45.723] Opening DataSocket to Port 2104**
I/flutter ( 5139): ERRORE_onProgressError: SocketException OS Error: Connection refused, errno = 111, address = 192.168.1.85, port = 56804
I/flutter ( 5139): file uploaded sucessfully
I/flutter ( 5139): [22.01.2022 09:23:00.445] Disconnecting...
I/flutter ( 5139): [22.01.2022 09:23:00.445] > QUIT
I/flutter ( 5139): [22.01.2022 09:23:01.457] < 150 Opening BINARY mode data connection.
I/flutter ( 5139): 425 Data channel timed out.
I/flutter ( 5139): 221 Goodbye.
I/flutter ( 5139): [22.01.2022 09:23:01.463] Disconnected!

The file is first uploaded to the ftp server but with a size of 0 bytes, then at the end of the uploading process it is deleted ... Why?

**Comment by salim-lachdhaf** [comment]
which version are you using ?

**Comment by federico2390** [comment]
Not work the image uploading...

**Comment by salim-lachdhaf** [comment]
could please check with the version just before

**Comment by federico2390** [comment]
1.0.0?

**Comment by salim-lachdhaf** [comment]
yes.

``Future<bool> uploadFile(
    File fFile, {
    String sRemoteName = '',
    TransferMode mode = TransferMode.binary,
    FileProgress? onProgress,
    bool supportIPV6 = true,
    bool checkTransfer = true,
  })``

other wise, try with different transfer mode, disable ipv6 ....

another thing, why i see in your log `ERRORE_onProgressError` please test pure ftp don't include other libraries

**Comment by federico2390** [comment]
I have just insert this print ERRORE_onProgressError in your on progress method on check error... i have also tryed disabling ipv6... another way i think is to share my desktop to fix this problem and then i paste here the solution to this problem for other users

**Comment by federico2390** [comment]
With V1.0.0

I/flutter (14761): [22.01.2022 13:52:59.921] Connecting...
I/flutter (14761): [22.01.2022 13:52:59.989] > USER sitolab@outlook.it
I/flutter (14761): [22.01.2022 13:53:00.811] < 220 Microsoft FTP Service
I/flutter (14761): 331 Password required
I/flutter (14761): [22.01.2022 13:53:00.813] > PASS Leccesidentro@1
I/flutter (14761): [22.01.2022 13:53:01.623] < 230 User logged in.
I/flutter (14761): [22.01.2022 13:53:01.624] Connected!
I/flutter (14761): [22.01.2022 13:53:01.625] > MKD Settimana 4 - 2022
I/flutter (14761): [22.01.2022 13:53:02.442] < 550 Cannot create a file when that file already exists.
I/flutter (14761): [22.01.2022 13:53:02.445] > CWD Settimana 4 - 2022
I/flutter (14761): [22.01.2022 13:53:03.253] < 250 CWD command successful.
I/flutter (14761): [22.01.2022 13:53:03.255] > CWD pippo
I/flutter (14761): [22.01.2022 13:53:04.065] < 250 CWD command successful.
I/flutter (14761): [22.01.2022 13:53:04.069] Upload File: /storage/emulated/0/Android/data/com.moeasy.are/cache/CAP1996679074750332207_cropped4361863381698870651.jpg
I/flutter (14761): [22.01.2022 13:53:04.071] Entering transfer mode TransferMode.binary
I/flutter (14761): [22.01.2022 13:53:04.072] > TYPE I
I/flutter (14761): [22.01.2022 13:53:04.882] < 200 Type set to I.
I/flutter (14761): [22.01.2022 13:53:04.883] > PASV
I/flutter (14761): [22.01.2022 13:53:05.692] < 227 Entering Passive Mode (192,168,1,85,14,49).
I/flutter (14761): [22.01.2022 13:53:05.703] > STOR CAP1996679074750332207_cropped4361863381698870651.jpg
I/flutter (14761): [22.01.2022 13:53:05.705] Opening DataSocket to Port 3633

![image](https://user-images.githubusercontent.com/42987961/150639376-d06edcf7-550d-4f20-8a0e-b60f5ef90c16.png)

**Comment by salim-lachdhaf** [comment]
did you gave all necessary permission to your app to access to your storage ... ?

**Comment by federico2390** [comment]
Yes 

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_INTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_INTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.INTERNET" />

**Comment by salim-lachdhaf** [comment]
the image upload is similar yo any other file upload. 
you can find a lot of example in unitTest or in example page.

check the run time permission , not only manifest permission

**Comment by federico2390** [comment]
I have test all your example... 
"check the run time permission " How?

**Comment by federico2390** [comment]
I solved it by enabling all inbound and outbound ports.
Do you have any advice not to open all the doors and maybe use a specific range?

**Comment by salim-lachdhaf** [comment]
i don't have, because the ftp how decide the the given port

**Comment by federico2390** [comment]
It's possible to upload multiple file ?
