### ISSUE TITLE
ftp connect IOS bug

### ISSUE THREAD

**Issue by akashiarnaud** [salim-lachdhaf/ftpConnect#49]
Hi

When I try to upload a file with IOS device in an FTP's folder, it returns this error:
FTPException: Could not start Passive Mode (Response: 500 Unknown command)
But it works fine with ANDROID device…

I already tried to set `supportIPV6=false` but it doesn't work.

Any ideas?

**Comment by salim-lachdhaf** [comment]
try to change the mode `TransferMode mode`. otherwises theres is no reason to have an error on ios but not an android except writing/reading file permission maybe.
