### ISSUE TITLE
ftpConnect.listDirectoryContent dose not return correct file name when the file name contains characters other than ascii

### ISSUE THREAD

**Issue by paulscliu** [salim-lachdhaf/ftpConnect#52]
listDirectoryContent currently only transfer in ascii mode. If the file name contains characters like Chinese, the returned file name will not be correct. Is it possilbe to add binary mode to listDirectoryContent?

**Comment by salim-lachdhaf** [comment]
yes, change transfer mode

**Comment by zhushenwudi** [comment]
> yes, change transfer mode

i change listDirectoryContent method's TransferMode to binary in directory.dart, but it also return correct name

**Comment by salim-lachdhaf** [comment]
so it's not a problem of transfer mode, you have to encode/decode the received name
