### ISSUE TITLE
flutter_test from sdk is incompatible with ftpconnect >=1.0.1.

### ISSUE THREAD

**Issue by federicofederigi** [salim-lachdhaf/ftpConnect#53]
i need to try version 1.0.1 to resolve problem of 1.0.0
i can not install ftpconnect 1.0.1
after     pub get
Because every version of flutter_test from sdk depends on path 1.8.0 and ftpconnect >=1.0.1 depends on path ^1.8.1, flutter_test from sdk is incompatible with ftpconnect >=1.0.1.
So, because rap_lav depends on both ftpconnect ^1.0.1 and flutter_test from sdk, version solving failed.
pub get failed (1; So, because rap_lav depends on both ftpconnect ^1.0.1 and flutter_test from sdk, version solving failed.)

**Comment by salim-lachdhaf** [comment]
use `override_dependencies` option on your yaml config file

**Comment by federicofederigi** [comment]
excuse me, i'm trying with 'override_dependencies' but don't resolve.

can you tell me the exact text i will type in pubspec,yaml ?

**Comment by Vorontsova1347** [comment]
> Because every version of flutter_test from sdk depends on path 1.8.0 and ftpconnect >=1.0.1 depends on path ^1.8.1, flutter_test from sdk is incompatible with ftpconnect >=1.0.1.

The solution is  to add this to yaml file:
```
dependency_overrides:
  path: ^1.8.1
```

**Comment by Sanlovty** [comment]
> excuse me, i'm trying with 'override_dependencies' but don't resolve.
> 
> can you tell me the exact text i will type in pubspec,yaml ?

Thje solution for your problem is :

```
dependency_overrides:
  path: ^1.8.1
```
