### ISSUE TITLE
PROT C is not allowed when control connection is secure. Use PROT P.

### ISSUE THREAD

**Issue by federicofederigi** [salim-lachdhaf/ftpConnect#55]
FTPS over TLS with FTPConnect 1.0.1  (android 10 virtualized and smartphone)
when i use filezilla client i'm connect to filezilla server with tls regulary
with ftp connect, instead. . . i receive the error:
PROT C is not allowed when control connection is secure. Use PROT P.

final FTPConnect _ftpConnect = FTPConnect("192.168.9.230",
    user: "federico",
    pass: "xxxxxx",
    port: 2121,
    //debug: true,
    debug: false,
    //isSecured: false,
    isSecured: true,
    timeout: 60
    );

I/flutter ( 6516): [10.03.2022 09:19:23.090] < 230 Login successful.
I/flutter ( 6516): [10.03.2022 09:19:23.092] Connected!
I/flutter ( 6516): [10.03.2022 09:19:23.121] Download /www.computer-line.it/rap-lav/rap-lav.zip to /data/user/0/it.computer_line.rap_lav/app_flutter/Rap-Lav/rap-lav.zip
I/flutter ( 6516): [10.03.2022 09:19:23.125] > SIZE /www.computer-line.it/rap-lav/rap-lav.zip
I/flutter ( 6516): [10.03.2022 09:19:23.931] < 213 146857
I/flutter ( 6516): [10.03.2022 09:19:23.951] Entering transfer mode TransferMode.binary
I/flutter ( 6516): [10.03.2022 09:19:23.955] > TYPE I
I/flutter ( 6516): [10.03.2022 09:19:24.778] < 200 Type set to I
I/flutter ( 6516): [10.03.2022 09:19:24.782] > EPSV
I/flutter ( 6516): [10.03.2022 09:19:25.589] < 229 Entering Extended Passive Mode (|||30000|)
I/flutter ( 6516): [10.03.2022 09:19:25.590] > RETR /www.computer-line.it/rap-lav/rap-lav.zip
I/flutter ( 6516): [10.03.2022 09:19:25.598] Opening DataSocket to Port 30000
I/flutter ( 6516): [10.03.2022 09:19:26.424] < 150 About to start data transfer.
I/flutter ( 6516): 425 Error while transfering data: PROT C is not allowed when the control connection is secure. Use PROT P.

![remmina_Federico               Nostro Server_192 168 9 230_20220308-155649](https://user-images.githubusercontent.com/77565275/157276611-f6ffaac9-1f82-4eed-94d1-cfde79877380.png)

**Comment by salim-lachdhaf** [comment]
you are showing me the same error in your fileZilla.
