### ISSUE TITLE
Active mode

### ISSUE THREAD

**Issue by mickbad** [salim-lachdhaf/ftpConnect#57]
Hello

thanks for your nice work 👍

is there a way to create an active mode for your plugin?

I have an automaton video recorder with ftp server. This server is only active mode. When I try to list a directory, I have this error: Passive Mode not implemented (due to ftp server)

Thanks in advance for your answer 

Mick

**Comment by ElksZero** [comment]
Hello.
The listdirectorycontent method and listdirectorycontentonlynames method cannot set the parameter "supportipv6", but the method they call requires "supportipv6". So "supportipv6" is actually true.

**Comment by mickbad** [comment]
Hello and thanks for the tips
Indeed when I set "supportipv6" to false, listing is ok with LIST command instead of MSLD
But downloading file failed due to firewall I think

(by the way, download with retry function not support ipv6 false)

I will close this "issue" when your're right with me (or ftp administrator open port :))

```
[15.04.2022 15:45:14.575] Download Untitled.txt to /tmp/Untitled.txt
 [15.04.2022 15:45:14.577] > SIZE Untitled.txt
 [15.04.2022 15:45:15.383] < 213 1270

 [15.04.2022 15:45:15.403] Entering transfer mode TransferMode.binary
 [15.04.2022 15:45:15.403] > TYPE I
 [15.04.2022 15:45:16.214] < 200 Command successful.

 [15.04.2022 15:45:16.222] > PASV
 [15.04.2022 15:45:17.035] < 227 Entering Passive Mode (10,192,241,41,224,39).

 [15.04.2022 15:45:17.041] > RETR Untitled.txt
 [15.04.2022 15:45:17.046] Opening DataSocket to Port 53996
 [15.04.2022 15:45:17.895] < 150 File status okay; about to open data connection.
250 Requested file action okay, completed.

 [15.04.2022 15:45:17.913] Start downloading...
[ERROR:state.cc(209)] Unhandled Exception: FTPException: Timeout reached for Receiving response ! (Response: null)
```

Am I right it's firewall is blocking?

very thanks :)

**Comment by salim-lachdhaf** [comment]
Sadly, i don't have an exact answer, it can be a large file, permission problem ,....

**Comment by mickbad** [comment]
Hello, you're right!

final issue was firewall state I think

2 things
* function downloadwithretry doesn't support ipv6 off
* when i download a file, remote server send me error 250 ... completed. And i have an exception with plugin
```
flutter: [20.04.2022 12:55:52.557] Download OverlayAbo.mov to toto.mov
flutter: [20.04.2022 12:55:52.565] > SIZE OverlayAbo.mov
flutter: [20.04.2022 12:55:53.416] < 213 1170912020

flutter: [20.04.2022 12:55:53.424] Entering transfer mode TransferMode.binary
flutter: [20.04.2022 12:55:53.425] > TYPE I
flutter: [20.04.2022 12:55:54.249] < 200 Command successful.

flutter: [20.04.2022 12:55:54.259] > PASV
flutter: [20.04.2022 12:55:55.068] < 227 Entering Passive Mode (10,192,241,41,255,79).

flutter: [20.04.2022 12:55:55.073] > RETR OverlayAbo.mov
flutter: [20.04.2022 12:55:55.075] Opening DataSocket to Port 65359
flutter: [20.04.2022 12:55:55.967] < 150 File status okay; about to open data connection.

flutter: [20.04.2022 12:55:55.981] Start downloading...
flutter: [20.04.2022 13:05:15.658] < 250 Requested file action okay, completed.

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FTPException: Transfer Error. (Response: 250 Requested file action okay, completed.)
```

download ok, file ok (correct movie here). Error 250 show it's ok but i have an exception

thanks very much for your future upgrade :)

have a nice day
Mick

**Comment by mickbad** [comment]
thanks for support, all right now except 250 error bad exception (it's manageable)
