### ISSUE TITLE
Some methods of ftpconnect have no way to set the parameter "supportIPV6", so they are forced to use the default value of true

### ISSUE THREAD

**Issue by ElksZero** [salim-lachdhaf/ftpConnect#58]
Hello!

First of all, thank you for your contribution.

This is a suggestion.

Why not add the "supportIPV6" attribute in the construction method of FTPConnect and use it in the corresponding methods to avoid setting "supportIPV6" every time these methods are called.

In addition, the method of "supportIPV6" is called in the "listDirectoryContentOnlyNames" method in FTPConnect, but these methods themselves can not pass in the middle note, which leads to the default use of "supportIPV6 = true". This is not friendly to FTP that does not support IPv6.

Please consider the suggestion。

Elkszero.

Translated by Baidu.

**Comment by salim-lachdhaf** [comment]
check the new version v2.0.0
