### ISSUE TITLE
upload file .txt

### ISSUE THREAD

**Issue by vohoangtuit** [salim-lachdhaf/ftpConnect#62]
i upload file .txt, i received a error with message is 'Null check operator used on a null value'. i checked path this file exists on my device

**Comment by vohoangtuit** [comment]
My code:
void _config(){
    _ftpConnect =FTPConnect('113.161.222.192',port: 2122,
        user: 'ftpuser', pass: 'Logitem@2020');
  }

  Future<bool> uploadFile(File fileToUpload) async {
    _log('fileToUpload ${fileToUpload.path}');
    _log('existsSync ${fileToUpload.existsSync()}');
    try {
      await _log('Connecting to FTP ...');
      await _ftpConnect!.connect();
      await _ftpConnect!.changeDirectory('test1');
      await _log('Uploading ...');
     await _ftpConnect!.uploadFileWithRetry(fileToUpload,pRetryCount: 2);
      await _ftpConnect!.disconnect();
      return true;
    }on SocketException catch (e) {
      _log('ERRORE_SocketException: ${e.message}');
      return false;
    }  catch (e) {
      await _log('Error upload: ${e.toString()}');
      return false;
    }
  }

My Log:

I/flutter ( 2939): file /sdcard/BarCodeScander/test.txt
I/flutter ( 2939): fileToUpload /sdcard/BarCodeScander/test.txt
I/flutter ( 2939): existsSync true
I/flutter ( 2939): Connecting to FTP ...
I/[MALI][Gralloc]( 2939): [+]r_hnd(0xb2fe5ce0), client(58), share_fd(63)
D/GraphicBuffer( 2939): register, handle(0xb2fe5ce0) (w:540 h:960 s:544 f:0x1 u:0x000b00)
D/libc-netbsd( 2939): [getaddrinfo]: netid=0; mark=0
D/libc-netbsd( 2939): [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=0
I/flutter ( 2939): Uploading ...
D/libc-netbsd( 2939): [getaddrinfo]: netid=0; mark=0
D/libc-netbsd( 2939): [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=0
I/flutter ( 2939): Error upload: Null check operator used on a null value

**Comment by salim-lachdhaf** [comment]
problem related to your server (check security param of your FTP server).
