### ISSUE TITLE
How to get output message and display in Flutter UI?

### ISSUE THREAD

**Issue by 13692277450** [salim-lachdhaf/ftpConnect#64]
Hi Salim,

I send a email to you hope you can advice how to get your ftp output messages and put into flutter UI, would you pls advice. I have a app and put on my website: www.pavogroup.top. 

many thanks for your kindly help
Mang Zhang/China
13692277450

**Comment by salim-lachdhaf** [comment]
sadly the log are printed to system log no to the UI.
you can take a look to the examples page to how i managed that.
