### ISSUE TITLE
How to check connection Object to null?

### ISSUE THREAD

**Issue by bubnenkoff** [salim-lachdhaf/ftpConnect#67]
Hi! I have got another question. I have got follow code:
```
    if( ftpConnect == null) {
      print("ftp connection become null");
      await ftpReconnect();
    }  
```
My connection Object:
```
late FTPConnect ftpConnect;
```
Should I do it like:
```
FTPConnect? ftpConnect;
```

But linter show me error: `The operand can't be null, so the condition is always false.
Try removing the condition, an enclosing condition, or the whole conditional statement`. How should I do this check?

Or there is some better way to check?

**Comment by bubnenkoff** [comment]
![изображение](https://user-images.githubusercontent.com/6514326/174133388-2a40b914-ac88-48a3-9bbd-97b7d90c3327.png)
I still can't understand how this can be possible. Null check is above.

**Comment by salim-lachdhaf** [comment]
could you past the content of `ftpReconnect()`

**Comment by bubnenkoff** [comment]
```
Future ftpReconnect() async {
    print("ftpReconnect");
    try {

        ftpConnect = getFTPConnection();
        await ftpConnect!.connect();


      } catch (e) {
        print('!Exeption in ftpReconnect: $e');
        
        sleep(Duration(seconds: 1));
        await ftpReconnect();
      }
          
}
```

**Comment by salim-lachdhaf** [comment]
from the code avove you forget qwait before `sleep`

**Comment by bubnenkoff** [comment]
Oh damn, thanks! I will recheck it without await. Give me few days

Пт, 17 июня 2022 г. в 23:27, Salim Lachdhaf ***@***.***>:
