### ISSUE TITLE
Unable to connect a secure server issecured set to true

### ISSUE THREAD

**Issue by aqueebqazi** [salim-lachdhaf/ftpConnect#68]
FTPException: Could not connect to bmw.eyebase.com (21) (Response: HandshakeException: Handshake error in client (OS Error: 
      	WRONG_VERSION_NUMBER(tls_record.cc:242)))

**Comment by salim-lachdhaf** [comment]
use secure mode.

**Comment by aqueebqazi** [comment]
using secure mode still not working
  FTPConnect ftpConnect = FTPConnect(
          // 'mediasuite5.eyebase.com',
          '${ftpcontroller.text}',
          port: int.parse(ports.text.toString()),
          user: username.text,
          pass: password.text,
          isSecured: true);

      await ftpConnect.connect();
      await ftpConnect.changeDirectory(defaultdirectory.text);
      await ftpConnect.disconnect();
