### ISSUE TITLE
getting this expection

### ISSUE THREAD

**Issue by aqueebqazi** [salim-lachdhaf/ftpConnect#71]
FTPException: Connection refused.  (Response: 521 PROT P required
      )
  await ftpConnect.connect();
          await ftpConnect.changeDirectory('Folder1');

          bool res = await ftpConnect.uploadFile(
            files,
          );
          await ftpConnect.disconnect();

**Comment by salim-lachdhaf** [comment]
have you an test ftp to use to check the exception ?

**Comment by aqueebqazi** [comment]
This expectation  occurs when the ftp server is configured with port p,right now we dont have any option for port p in the libary

**Comment by salim-lachdhaf** [comment]
check the new version v2.0.0
