### ISSUE TITLE
Ftps on ftpConnect

### ISSUE THREAD

**Issue by Toavina23** [salim-lachdhaf/ftpConnect#72]
It says that I need to use PROT P instead of PROT C in order to use ftps but i don't know where to specify that.
Note: I have already enabled secure connection on the FTPConnect instance

**Comment by salim-lachdhaf** [comment]
we will fix that , thank you for reporting

**Comment by Toavina23** [comment]
thanks for your fast reply, I really love this package

**Comment by salim-lachdhaf** [comment]
check the new version v2.0.0
