### ISSUE TITLE
File upload error

### ISSUE THREAD

**Issue by ShaneDiNozzo** [salim-lachdhaf/ftpConnect#73]
Hi!

When I try to upload a file to a Microsoft FTP server, the following message appears:
534 Policy requires SSL
How can I configure this in the library?
Thank you in advance!

**Comment by salim-lachdhaf** [comment]
try with `isSecure` to true

**Comment by ShaneDiNozzo** [comment]
Thank you for your answer!
I've already set `isSecure` to `true`.

The debug log is the following:
`
I/flutter (30322): [08.08.2022 15:51:51.357] Connecting...
I/flutter (30322): [08.08.2022 15:51:51.620] > AUTH TLS
I/flutter (30322): [08.08.2022 15:51:52.452] < 220 Microsoft FTP Service
I/flutter (30322): 234 AUTH command ok. Expecting TLS Negotiation.
I/flutter (30322): [08.08.2022 15:51:52.589] > USER exampleuser
I/flutter (30322): [08.08.2022 15:51:53.400] < 331 Password required
I/flutter (30322): [08.08.2022 15:51:53.401] > PASS examplepassword
I/flutter (30322): [08.08.2022 15:51:54.207] < 230 User logged in.
I/flutter (30322): [08.08.2022 15:51:54.208] Connected!
I/flutter (30322): [08.08.2022 15:51:54.235] Upload File: example_image.jpg
I/flutter (30322): [08.08.2022 15:51:54.240] Entering transfer mode TransferMode.binary
I/flutter (30322): [08.08.2022 15:51:54.243] > TYPE I
I/flutter (30322): [08.08.2022 15:51:55.052] < 200 Type set to I.
I/flutter (30322): [08.08.2022 15:51:55.055] > EPSV
I/flutter (30322): [08.08.2022 15:51:55.862] < 229 Entering Extended Passive Mode (|||7002|)
I/flutter (30322): [08.08.2022 15:51:55.909] > STOR example_image.jpg
I/flutter (30322): [08.08.2022 15:51:55.914] Opening DataSocket to Port 7002
I/flutter (30322): [08.08.2022 15:52:28.006] Upload File: example_image.jpg
I/flutter (30322): [08.08.2022 15:52:28.007] > EPSV
I/flutter (30322): [08.08.2022 15:52:29.010] < 534 Policy requires SSL.
I/flutter (30322): 229 Entering Extended Passive Mode (|||7003|)
I/flutter (30322): [08.08.2022 15:52:29.012] > STOR example_image.jpg
I/flutter (30322): [08.08.2022 15:52:29.013] Opening DataSocket to Port 7003
`

The after this it throws an `Unhandled Exception: SocketException: Connection timed out` exception.

**Comment by salim-lachdhaf** [comment]
thank you for this detailed log, have you a test account to test from my side (if so, send it via email).

**Comment by ShaneDiNozzo** [comment]
It is on a corporate network that can't be accessed from outside and they don't let me to do that.

The server is using the FTP over explicit TLS protocol.

I have found some kind of a solution on the Android side, but I can't test it. [https://stackoverflow.com/questions/21453716/android-ftp-file-tranfer-over-explicit-tls](url)
Maybe something to do with accepting the certificates.

**Comment by salim-lachdhaf** [comment]
check the new version v2.0.0
