### ISSUE TITLE
FTPException: Could not start Passive Mode (Response: 500 'EPSV': command not understood.

### ISSUE THREAD

**Issue by remsysinc** [salim-lachdhaf/ftpConnect#74]
Hello.  Getting this error using FTPConnect in Flutter when trying to upload a file.  I connect fine.

I have another FTP client program accessing the server using "passive mode" so I believe this issue is client-side.

Is there a way with your plug-in to set the mode to "passive"?  Would appreciate any feedback to get around this error.

Thank you.

**Comment by salim-lachdhaf** [comment]
check the new version v2.0.0

**Comment by remsysinc** [comment]
Will do - thank you!
