### ISSUE TITLE
Response: Unsupported operation: RawSocket constructor

### ISSUE THREAD

**Issue by juspitt-lts** [salim-lachdhaf/ftpConnect#75]
Getting the following error does this support ftp on local networks, its not for outside access.

FTPException: Could not connect to 192.168.25.11 (21) (Response: Unsupported operation: RawSocket constructor)

FTPConnect ftpConnect = FTPConnect('192.168.25.11',
        user: '**********',
        pass: '**********',
        port: 21,
        debug: true,
        isSecured: false);
    try {
      File fileToUpload = File(_file);
      await ftpConnect.connect();
      await ftpConnect.uploadFile(fileToUpload);
      await ftpConnect.disconnect();
    } catch (e) {
      //error
      print(e.toString());
    }

**Comment by cengizhanas** [comment]
same issue

**Comment by salim-lachdhaf** [comment]
check the new version v2.0.0

**Comment by cengizhanas** [comment]
Same

**Comment by salim-lachdhaf** [comment]
did you tried with different security type ?
if yes, did fileZilla works well ?

**Comment by cengizhanas** [comment]
yes i tried SecurityType.FTP and FTPS .yes i checked filezilla it work well

**Comment by salim-lachdhaf** [comment]
Could not connect to 192.168.25.11 means only one thing , you have not access to that address, or your port is wrong.

**Comment by cengizhanas** [comment]
i can access with Js.my user,and password everthing is correct but when i try to connect with flutter(Web) i took error

**Comment by salim-lachdhaf** [comment]
ah now i understand, sadly this lib doesn't support web.
you can check that on pub.dev page.
