### ISSUE TITLE
listDirectoryContent() and listDirectoryContentOnlyNames() not working.

### ISSUE THREAD

**Issue by TakaTeke** [salim-lachdhaf/ftpConnect#76]
Dear Salim Lachdhaf

I am using ftpconnect that you created.
I want to list the contents of a directory from my host's FTP server, but when I run listDirectoryContent() or listDirectoryContentOnlyNames() I get the following error:
                  .
                  .
flutter: [24.09.2022 13:28:44.903] > MLSD
flutter: [24.09.2022 13:28:44.917] < FTPReply = [code= 502, message= 502 Command not implemented (MLSD).]
flutter: Error: FTPException: Connection refused. (Response: 502 Command not implemented (MLSD).)

Should I just use ListCommand? But I don't know how to use ListCommand.
It would be helpful if you could tell me how to solve it.
thank you.

**Comment by salim-lachdhaf** [comment]
it seems that your server does not support `MLSD` command.

in this case try another option from this list :  `{ NLST, LIST, MLSD }`

like this: yourFtpConnect.setListCommand(ListCommand.LIST)

**Comment by TakaTeke** [comment]
Thank you for your prompt reply.
I tried to write as you instructed,
myFtpConnect.setListCommand(ListCommand.LIST)
But I get an error like below.

The method 'setListCommand' isn't defined for the type 'FTPConnect'. (Documentation) Try correcting the name to the name of an existing method, or defining a method named 'setListCommand'.

'sendCustomCommand'?
I tried the following,
myFtpConnect.sendCustomCommand('PASV')
myFtpConnect.sendCustomCommand('LIST')
However, I got an error due to timeout as below.
flutter: Error: FTPException: Timeout reached for Receiving response ! (Response: null)

What should I do?

**Comment by TakaTeke** [comment]
You edited it. Thank you.
myFtpConnect.listCommand(ListCommand.LIST)
I tried, but I get the following error.

The method 'listCommand' isn't defined for the type 'FTPConnect'. (Documentation)  Try correcting the name to the name of an existing method, or defining a method named 'listCommand'.

If you have any further advice, please let me know.

**Comment by salim-lachdhaf** [comment]
https://github.com/salim-lachdhaf/ftpConnect/blob/79082cf279f7a537ee407995f9f69dcb4722a2b9/test/ftpConnect_test.dart#L123
