### ISSUE TITLE
FTPS doesn't work

### ISSUE THREAD

**Issue by khomin** [salim-lachdhaf/ftpConnect#81]
flutter: [04.10.2022 21:57:17.853] Connecting...
flutter: [04.10.2022 21:57:18.528] Connection established, waiting for welcome message...
flutter: [04.10.2022 21:57:18.841] < FTPReply =  [code= 220, message= 220 FTP Server 1.0]
flutter: [04.10.2022 21:57:18.842] > AUTH TLS
flutter: [04.10.2022 21:57:19.148] < FTPReply =  [code= 234, message= 234 AUTH TLS successful]
flutter: [04.10.2022 21:57:19.365] > PBSZ 0
flutter: [04.10.2022 21:57:19.670] < FTPReply =  [code= 200, message= 200 PBSZ 0 successful]
flutter: [04.10.2022 21:57:19.670] > PROT P
flutter: [04.10.2022 21:57:19.971] < FTPReply =  [code= 200, message= 200 Protection set to Private]
flutter: [04.10.2022 21:57:19.971] > USER xxxxx
flutter: [04.10.2022 21:57:20.272] < FTPReply =  [code= 331, message= 331 Password required for xxxxx]
flutter: [04.10.2022 21:57:20.272] > PASS xxxxxxxxx
flutter: [04.10.2022 21:57:20.574] < FTPReply =  [code= 230, message= 230 User xxxxx logged in]
flutter: [04.10.2022 21:57:20.574] Connected!
flutter: [04.10.2022 21:57:20.577] Download test.txt to /Users/xxxxx/update_info.json
flutter: [04.10.2022 21:57:20.578] > SIZE test.txt
flutter: [04.10.2022 21:57:20.879] < FTPReply =  [code= 550, message= 550 SIZE not allowed in ASCII mode]
flutter: [04.10.2022 21:57:20.880] > TYPE I
flutter: [04.10.2022 21:57:21.180] < FTPReply =  [code= 200, message= 200 Type set to I]
flutter: [04.10.2022 21:57:21.181] > SIZE test.txt
flutter: [04.10.2022 21:57:21.481] < FTPReply =  [code= 213, message= 213 76886]
flutter: [04.10.2022 21:57:21.483] > PASV
flutter: [04.10.2022 21:57:21.784] < FTPReply =  [code= 227, message= 227 Entering Passive Mode (136,243,166,47,201,244).]
flutter: [04.10.2022 21:57:21.785] > RETR test.txt
flutter: [04.10.2022 21:57:21.785] Opening DataSocket to Port 51700
flutter: [04.10.2022 21:57:22.173] < FTPReply =  [code= 150, message= 150 Opening BINARY mode data connection for test.txt (76886 bytes)]
flutter: [04.10.2022 21:57:22.173] Start downloading...

That - "downloading" stays for very long and nothing changes

**Comment by salim-lachdhaf** [comment]
check the last version 2.0.3.
