### ISSUE TITLE
uploadFile() method does not wait for the end of the execution

### ISSUE THREAD

**Issue by LuscapLudovic** [salim-lachdhaf/ftpConnect#84]
I have a method that take picture and upload it to a ftps server. I need high quality picture so my file's size is around 3,8Mo.
But when i use ftpConnect.uploadFile().

With the debug option I saw this:
I/flutter (10710): [21.11.2022 14:51:10.250] Connecting...
I/flutter (10710): [21.11.2022 14:51:10.385] Connection established, waiting for welcome message...
I/flutter (10710): [21.11.2022 14:51:10.706] < FTPReply =  [code= 220, message= 220 Microsoft FTP Service]
I/flutter (10710): [21.11.2022 14:51:10.708] > AUTH TLS
I/flutter (10710): [21.11.2022 14:51:11.017] < FTPReply =  [code= 234, message= 234 AUTH command ok. Expecting TLS Negotiation.]
I/flutter (10710): [21.11.2022 14:51:11.110] > PBSZ 0
I/flutter (10710): [21.11.2022 14:51:11.420] < FTPReply =  [code= 200, message= 200 PBSZ command successful.]
I/flutter (10710): [21.11.2022 14:51:11.421] > PROT P
I/flutter (10710): [21.11.2022 14:51:11.723] < FTPReply =  [code= 200, message= 200 PROT command successful.]
I/flutter (10710): [21.11.2022 14:51:11.723] > USER user
I/flutter (10710): [21.11.2022 14:51:12.026] < FTPReply =  [code= 331, message= 331 Password required]
I/flutter (10710): [21.11.2022 14:51:12.028] > PASS pass
I/flutter (10710): [21.11.2022 14:51:12.330] < FTPReply =  [code= 230, message= 230 User logged in.]
I/flutter (10710): [21.11.2022 14:51:12.331] Connected!
I/flutter (10710): Connection : SUCCESSFULLY
I/flutter (10710): [21.11.2022 14:51:13.342] > CWD palette
I/flutter (10710): [21.11.2022 14:51:13.645] < FTPReply =  [code= 250, message= 250 CWD command successful.]
I/flutter (10710): Change directory : SUCCESSFULLY
I/flutter (10710): Uploading ... : File: '/sdcard/Download/testllu.jpg'
I/flutter (10710): [21.11.2022 14:51:16.170] Upload File: /sdcard/Download/testllu.jpg
I/flutter (10710): [21.11.2022 14:51:16.177] > PASV
I/flutter (10710): [21.11.2022 14:51:16.484] < FTPReply =  [code= 227, message= 227 Entering Passive Mode (172,30,10,93,207,152).]
I/flutter (10710): [21.11.2022 14:51:16.487] > STOR testllu.jpg
I/flutter (10710): [21.11.2022 14:51:16.491] Opening DataSocket to Port 53144
I/flutter (10710): [21.11.2022 14:51:16.844] < FTPReply =  [code= 150, message= 150 Opening ASCII mode data connection.]
I/flutter (10710): [21.11.2022 14:51:16.847] Start uploading...
I/flutter (10710): percent: 1.56 / received: 65536 / fileSize: 4189590
I/flutter (10710): percent: 3.13 / received: 131072 / fileSize: 4189590
I/flutter (10710): percent: 4.69 / received: 196608 / fileSize: 4189590
I/flutter (10710): percent: 6.26 / received: 262144 / fileSize: 4189590
I/flutter (10710): percent: 7.82 / received: 327680 / fileSize: 4189590
I/flutter (10710): percent: 9.39 / received: 393216 / fileSize: 4189590
I/flutter (10710): percent: 10.95 / received: 458752 / fileSize: 4189590
E/flutter (10710): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Write failed (OS Error: Connection reset by peer, errno = 104), address = 172.30.10.93, port = 39376
E/flutter (10710): 0      _NativeSocket.write (dart:io-patch/socket_patch.dart:1190:34)
E/flutter (10710): 1      _RawSocket.write (dart:io-patch/socket_patch.dart:1916:15)
E/flutter (10710): 2      _Socket._write (dart:io-patch/socket_patch.dart:2356:18)
E/flutter (10710): 3      _SocketStreamConsumer.write (dart:io-patch/socket_patch.dart:2104:26)
E/flutter (10710): 4      _SocketStreamConsumer.addStream.<anonymous closure> (dart:io-patch/socket_patch.dart:2078:11)
E/flutter (10710): 5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (10710): 6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (10710): 7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (10710): 8      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
E/flutter (10710): 9      _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
E/flutter (10710): 10     FileUpload.uploadFile.<anonymous closure> (package:ftpconnect/src/commands/file_upload.dart:58:16)
E/flutter (10710): 11     _HandlerEventSink.add (dart:async/stream_transformers.dart:209:17)
E/flutter (10710): 12     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
E/flutter (10710): 13     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (10710): 14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (10710): 15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (10710): 16     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
E/flutter (10710): 17     _StreamController._add (dart:async/stream_controller.dart:648:7)
E/flutter (10710): 18     _StreamController.add (dart:async/stream_controller.dart:596:5)
E/flutter (10710): 19     _FileStream._readBlock.<anonymous closure> (dart:io/file_impl.dart:98:19)
E/flutter (10710): <asynchronous suspension>

this is my method: 
```  Future<void> uploadFtp(File filepath, String code) async {
    var cnx = await connectFTP();
    try {
      bool change = await cnx.changeDirectory('palette');
      await _log(
          'Change directory : ' + (change ? 'SUCCESSFULLY' : 'FAILED'));
      String newName = join('/sdcard/Download/', '$code.jpg');
      filepath = File(filepath.path);
      File moving = await moveFile(filepath, newName);
      await _log('Uploading ... : ${moving}');
      cnx.uploadFile(moving, onProgress: (percent, received, fileSize) {
        print('percent: $percent / received: $received / fileSize: $fileSize');
      }).then((value) async {
        await _log('file uploaded successfully');
        await cnx.disconnect();
        final del = Directory(moving.path);
        del.deleteSync(recursive: true);
      });
    } catch(e) {
      await _log('Error: ${e.toString()}');
    }
  }
```

In file_upload.dart the error occurs at this point : 
![image](https://user-images.githubusercontent.com/16818782/203074194-2d51016f-fd05-4314-936b-2d6043c35a6c.png)

I don't have any problem with small files (<100ko).

**Comment by salim-lachdhaf** [comment]
check the last version 2.0.3.
