### ISSUE TITLE
Got no route exception

### ISSUE THREAD

**Issue by zzzh** [salim-lachdhaf/ftpConnect#85]
Hi, I was trying to run ftpConnect on my Android phone to access a running ftp server, both  in same LAN, connected to a router by wifi.

I'm also sure the ftp server is running well, since I can access it on my computer ( also in same LAN) by FileZilla.

So I have no idea why this exception appears:
FTPException (FTPException: Could not connect to 192.168.1.103 (21) (Response: SocketException: No route to host (OS Error: No route to host, errno = 113), address = 192.168.1.103, port = 57956))

192.168.1.103 is the ip address of ftp server.

 any ideas ?

**Comment by salim-lachdhaf** [comment]
make sure that you are connect to the same network as your server.
